### ISSUE TITLE
API seems to be down

### ISSUE THREAD

**Issue by Simboubou** [Equim-chan/tensoul#1]
Hello there,

I've been using akochan-reviewer for a while (thank you so much for this program !).

Today, the reviewer is not working anymore. It looks like the call to the tensoul API is not working anymore. Is it a temporary issue with herokuapp or was it taken down ?

Thanks !

**Comment by Equim-chan** [comment]
Sorry my bad, it should be fixed now.

**Comment by Simboubou** [comment]
Indeed, it works. Thanks again for the reviewer ! 👍
