### ISSUE TITLE
Can akochan work on atamahane-Rule?

### ISSUE THREAD

**Issue by Remainedwold** [Equim-chan/tensoul#3]
For making akochan analyze paifu on professional league rules, one can make paifu file on json but should make rule in atamehane for common as many professional rules contains atamahane.
There's agari.cpp code which is coded about tsumo and ron. Can I adjust this one and make atamahane work on akochan analyze?

**Comment by Equim-chan** [comment]
You should ask this in [critter-mj/akochan](https://github.com/critter-mj/akochan).
